### ISSUE TITLE
Please prompt "Are you sure?" before destroying user entered data

### ISSUE THREAD

**Issue by jleaders** [MBulli/SmartCommandlineArgs#105]
I kept adding data to
`Debug > Project Debug Properties > Debugging > Command Arguments`
and it kept getting silently deleted in the background by the plugin. I lost a few hours due to this behavior because I forgot I had installed this plugin last week.

If `Command Arguments` is a non-empty string, the plugin should prompt with a modal 
**"Are you sure you'd like to erase the arguments?"**

Deleting user data without a prompt violates Microsoft release standards.
Thanks

**Comment by MBulli** [comment]
I unterstand your request but this is by design. If you have our extensions window loaded (meaning visible or minimized) our extension is active and will set the project properties if you start your project. This is actually stated on our page here on GitHub
`If the Window is open or minimized the commandline arguments should not be edited via the project properties.`

Still, we will think about this issue and if we can find a way to improve the user experience in all use cases.
