### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by DanielPa** [MBulli/SmartCommandlineArgs#108]
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by MBulli** [comment]
At the moment `SmartCmdArgs.dll` only references VS2015 dependencies. With VS2017 we added a dynamically loaded assembly `SmartCmdArgs15.dll` which implements the new project system. This also worked well with VS2019.

Now with VS2022 we HAVE to link to the latest VS SDK which would break older VS versions. This means we have to stop developing for older versions or split our extension into several extensions. The we avoided the former because we want everyone to benefit from bug fixes and new features. We also avoided the latter to not to loose our user base because they have to look up a new extension in the marketplace.

MS writes on their migration docs:
`In the future, the Marketplace will allow you to upload multiple VSIXs to just one Marketplace listing. You can then upload your Visual Studio 2022-targeted VSIX and a VSIX for an earlier version of Visual Studio. Your users will automatically get the right VSIX for the Visual Studio version they've installed, when they're using the Visual Studio extension manager.`

This would be perfect but it is unknown when we'll in this bright future. So for now we planning to do some bugfixing with the current code and try to push a new version to the marketplace. After that we'll have to modernize our code base which will allow us to migrate to VS2022. Then we will release a VS2022 version. After that we wait for MS to enable us to upload several vsix files to the marketplace.

sigh ...

**Comment by MBulli** [comment]
Related to #96

**Comment by Irame** [comment]
You can download the vsix for VS 2022 here: https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.3.0

But this version is currently not uploaded to the marketplace. We will publish the 2022 version to the marketplace in the future.

**Comment by Irame** [comment]
New bugfix version: https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.3.1

**Comment by Irame** [comment]
After quite a long wait, we finally uploaded a official version to the marketplace:
https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments2022
