### ISSUE TITLE
no documentation on how to restore 

### ISSUE THREAD

**Issue by jgoebec** [MBulli/SmartCommandlineArgs#129]
This program should provide the option to respect existing arguments for each configuration.  As it stands, as soon as it is installed, it blows over your existing args so you can't execute how you were executing.  Deleting or disabling the extension does not restore the old style.  This has effectively rendered several of my repo's useless.

The installation documents mention that the old commands are moved into the .suo-file, but it doesn't document how to actually restore things and the extension doesn't do it automatically, so it leaves users stuck in a bad place.

**Comment by MBulli** [comment]
Sorry to hear that. That's actually something we hear not often but regularly. If you have an idea how we should change the extension to improve this issue please let us know. 

We planning to add a mode where the extension is doing nothing if it sees a project for the first time. The use than needs to click on a button to transfer the command lines from the visual studio project into the extension.

However, we can't restore the commands when the extension is disabled or uninstalled. Because we can't execute code on every project on which extension was ever active. What you can do is to enable all commands in our UI and then remove the extension.

Maybe you can get your command lines back. There should be a json file next to your project. In that file all command lines are stored. Or if you had git support disabled the json string is in the suo. I don't know if it is feasible to recover the data from there.
