### ISSUE TITLE
Add ENV var support

### ISSUE THREAD

**Issue by dbgarlisch** [MBulli/SmartCommandlineArgs#136]
Similar to command line args, being able to define and manage and group ENV vars on a per-project basis would be spectacular.

For debugging, I often find myself needing to change env vars at the same time I am changing command line args.

My debugging life would be much simplified and less error prone if I could group them together.

Basically, controlling Arguments, [working directory (#98)][98], and environment on a per-project basis would be perfect.

[98]: https://github.com/MBulli/SmartCommandlineArgs/issues/98

**Comment by vrubleg** [comment]
As an idea how it could be added to the current interface. All items in the table could have type, by default the type is `cmd` (it could be displayed on a 16x16 icon before text, like groups of parameters have the icon of folder), but it could be changed to `env` (where the string should be in format NAME=value or NAME= for empty environment variable) or `dir`/`cd`/`wd` (where the string is working directory).

Working directory should be selected by radio buttons instead of checkboxes. If a group of parameters have a working directory inside, the whole group should use a radio button then. It can be useful when you have a few sets of parameters for testing (e.g. for different use cases) that should use different working directories.

It's just an idea how it could be integrated into interface without bloating it. The plugin is very valuable in current state, support of setting environment variables and working directory would just make it more powerful and cover all possible cases related to testing command line programs.

**Comment by Irame** [comment]
That's funny I was thinking about the exact same solution for ENV vars.

But I think that the solution for working directory isn't that easy. 
- If you have multiple different groups with working directories than we also make sure that only one is selectable.
- If there are multiple working directories in different groups for different "Project Configurations" than they could be selected at the same time because they will never be applied simultaneously.
- But what happens then, if someone changes the "Project Configuration".

My "solution" would be to add a option like "Working Directories" to groups but only one group can have this option set. This group then has exclusive mode enabled and everything inside it is treated as a working directory.

**Comment by vrubleg** [comment]
Maybe it can be resolved in a simpler way.

It is possible that there are duplicates of ENV variables. It is safe to assume that the last ENV variable with the same name wins. Similar approach could be applied to working directory: the last active one is actually used. Unused duplicates can be just grayed out in the table.

**Comment by Irame** [comment]
implemented in e5a6599832a2ff9a30d6fb9bebab90dc0bbad98c

**Comment by dbgarlisch** [comment]
Thank you!

**Comment by Irame** [comment]
You're welcome!

I have a question about a feature. I thought about adding the option to change an item from CLA to ENV and back (right now, to create an ENV item, you click the small arrow next to the plus-icon and choose "Add new Environment Variable"). I added this feature but then removed it because I thought it would make the context menu too crowded. But now I think that when you copy and paste text or files, it only makes normal CLAs. Would giving an option to change the item type be a good way to include this function for ENV items without bothering regular users too much? What do you think?

**Comment by dbgarlisch** [comment]
I am not understanding what you are describing.

Maybe after I have had a chance to use the new env feature, I will be able to give a more informed answer.

Is there a release date for the env feature?

**Comment by Irame** [comment]
Ok sorry I didn't describe it properly. I think I will add the option anyway and you can let me know what you think.

I think I will release a new version in the next two weeks.

**Comment by Irame** [comment]
FYI: This is now available in [v2.6.0](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.6.0)

**Comment by Irame** [comment]
Did you enable environment variables in the extension (either in the options panel or the settings dialog)? I disabled it by default so existing projects don't break. I was thinking about a button or something to import existing variables when activating this feature but for now you have to add them manually.

As for the support of VC++ project. It depends on the debugger used. There is a list at [ProjectArguments.cs:159](https://github.com/MBulli/SmartCommandlineArgs/blob/5d5176203bbcfccbffea76531aeb37d5e8eb33c2/SmartCmdArgs/SmartCmdArgs.Shared/Helper/ProjectArguments.cs#L159) wich contains all supported debuggers. Missing flavors can be gathered in issue #155 I created for that.

**Comment by vrubleg** [comment]
Yes, it was turned on. I restarted Visual Studio, and it started to work. Maybe initial setting values were cached somewhere and updated settings weren't taken into account.

**Comment by dbgarlisch** [comment]
Just updated to the new ENV version.

It.... is.... spectacular!

Having both ENV and command line args in one place will make my debugging life SOOOO much simpler and less error prone.

Thank you again.
