### ISSUE TITLE
Arguments lost when restarting VS

### ISSUE THREAD

**Issue by markusburetorp** [MBulli/SmartCommandlineArgs#15]
First of all, I love how this extension improves the command line UI. But I have one major flaw and that is that most of the time (but not all the time) the *.args.json file is not loaded when I restart VS. If I close VS at that point it erases all contents of the .args.json file which is very annoying.

I don't have any repro steps at this point. What is the GUID for in the json-file? I noticed that the GUID is different every time.

**Comment by MBulli** [comment]
Hi there, I'm happy you like our extension. Although that bug is a bummer!

The GUID is required to map the tick state which is stored inside the suo file to the command inside the json file. We decided to use GUIDs to be independent of the order etc. The extension really doesn't care if the ID is changing, it just looses the state of the checkboxes.

It's hard to tell why you experiencing this behavior. It seems like, that the extensions fails to load the json file and then assumes a empty list. 

Let me try to ask some questions to narrow down the problem:
What kind of project are you using? What's your system language? Is your project stored inside a special folder of any kind? Is the json file empty after you added a command and clicked 'save all' in VS?

Thanks.

**Comment by markusburetorp** [comment]
Hi,

I'm using C++ in VS 2015. It does save the arguments just fine.

Now when I try it seems that it reads the arguments just fine if I double click on the .sln file but fails to read them if I load the solution from the File -> Recent Projects and Solutions menu. It also fails if I set the solution as a startup solution (auto load). Could it be that simple?

For example, if I double click on my solution file it is all good. But if I close the solution (File -> Close Solution) and open it again from the Recent menu the arguments are all gone.

**Comment by MBulli** [comment]
Hi,

we couldn't repo this but we added some logging code.
Please install the [beta release](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v1.2.1-beta) which contains the logging code.

The extension will log to the [visual studio activity log](https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/). You need to pass the /Log commandline parameter to devenv to enable the log. The log is stored at `%APPDATA%\Microsoft\VisualStudio\14.0\ActivityLog.xml`. I suggest to delete the old log file first. 

We're logging the absolute path to the json file make sure it doesn't leak any sensitive information.

Thank you.

**Comment by markusburetorp** [comment]
I figured this out myself actually, and it was my fault. My solution and projects files are generated by a script and after some struggle I found out that my project type GUID in the .sln file was wrong. Apparently that GUID acts as some project language identifier (not sure where that is used though). So I changed from a randomly generated GUID to the pre-defined C++ GUID.

After correcting this your plugin works as expected! :)
