### ISSUE TITLE
Changes to arguments after pressing F5 with a build are ignored

### ISSUE THREAD

**Issue by djfooks** [MBulli/SmartCommandlineArgs#158]
To reproduce

1. Make a change to a cpp
2. Hit F5 and chose to build
3. Change an argument while the build is ongoing

Observe that the application is not started with the changed arguments. Stopping and starting again gets the new arguments.

**Comment by Irame** [comment]
This happens because we only update the project configuration on the "ProjectBeforeRun" event ([see code](https://github.com/MBulli/SmartCommandlineArgs/blob/v2.6.0/SmartCmdArgs/SmartCmdArgs.Shared/VisualStudioHelper.cs#L413)).

The solution to you problem would be to also update the configuration every time the tree is changed. I don't know if that would bring some unwanted side effects, but I think it would be fine.

This would also fix #65.
