### ISSUE TITLE
For an UWP App the parameters are not passed to app

### ISSUE THREAD

**Issue by DorelPislan** [MBulli/SmartCommandlineArgs#159]
If I set them in Visual Studio (_Project Properties->Configuration Properties->Debugging -> Command Line Arguments_) they are accessible in argument of  `Application::OnLaunched() `entry point.

**Comment by Irame** [comment]
Yes sadly UWP and C# projects differ in the way they store the command line arguments.
For C# projects there are stored under `<StartArguments>` in the "*.csproj.user" file, but for UWP apps they are stored under `<CommandLineArguments>`. This means that we need to distinguish between those two.

As of now I couldn't find a way to do that via the VisualStudio API, because [`IVsHierarchy.GetProperty`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivshierarchy.getguidproperty) with [`VSHPROPID_TypeGuid`](https://learn.microsoft.com/de-de/dotnet/api/microsoft.visualstudio.shell.interop.__vshpropid) only returns the GUID for a normal C# project. The only way I can currently think of, is to read the content of the "*.csproj" file directly and check if the `<ProjectTypeGuids>` contain `A5A43C5B-DE2A-4C0C-9213-0A381AF9435A`.

If someone has a better idea I am open for it.
