### ISSUE TITLE
.args.json file way to specify that an option should be default checked

### ISSUE THREAD

**Issue by djfooks** [MBulli/SmartCommandlineArgs#168]
Is it possible to specify that a command should have its checkbox ticked by default?

I've tried the following
    {
      "Id": "a47748fd-98cb-4b2e-a65a-6ddd84ac4d00",
      "Command": "-o",
      "Enabled": true,
      "Value": true,
      "DefaultChecked": true
    },

but none of these work.

**Comment by Irame** [comment]
Hi, thanks for using the extension and reaching out about your problem. I was inactive for a while on this project, I'm sorry.

To be on the same page here, what is your expected behavior of an item that is "default checked"?
The current behavior is that if "default checked" is set and the item is first loaded on your copy of the project the item is checked automatically. A second feature is, that you can reset all or some items to the "default checked" state.

The way you showed is on way to set "default checked", another is to use the context menu.

**Comment by Irame** [comment]
I thought about your problem a bit and noticed that I was mistaken. The "default checked" functionality like I described it does not exist. I even create a issue (#153) for it but it was so long ago that I didn't think of that.

I'll say this issue here is a duplicate and I will think about a solution for this problem. Any further discussion should happen in the linked Issue.
