### ISSUE TITLE
Doesn't seem to work for VB.NET projects

### ISSUE THREAD

**Issue by BlueNinjaSoftware** [MBulli/SmartCommandlineArgs#19]
I have tried using this extension with both a C# and VB.NET console project, but it doesn't seem to pass the parameters to the VB.NET project. My goal was to use it with a VB.NET console project but it wouldn't pass the enabled args, so I tried making an empty C# project to test, and that worked. Tried an empty VB.NET project, and it didn't. I couldn't find anything in the docs or Google search about having to do anything different or specific for VB, and the docs say it works with both C# and VB.NET. So, am I doing something wrong or missing something that's gonna make me feel like an idiot? :)

I did clone the repo to poke around the code and see if anything jumps out at me, but I haven't done VS extensions before so I'm not sure how helpful I'll be.

**Comment by Irame** [comment]
Hi,
thanks for your detailed bug report.
This issue should be fixed with commit c868d392b305226d20dbb484f26b7679a3eda125.
You can use [SmartCmdArgs.zip](https://github.com/MBulli/SmartCommandlineArgs/files/629281/SmartCmdArgs.zip) until the fixed version is available as an update in the VisualStudio gallery.

**Comment by BlueNinjaSoftware** [comment]
Wow, that was fast - thanks!
