### ISSUE TITLE
Doesn't seem to work for .NET Core project

### ISSUE THREAD

**Issue by thomaslevesque** [MBulli/SmartCommandlineArgs#46]
I have a .NET Core 2.0 console app. I added some command line arguments via this tool, but when I run the app, `args` is always empty. Am I missing something?

**Comment by thomaslevesque** [comment]
In fact, it never changes the arguments in the debug settings

**Comment by thomaslevesque** [comment]
I'm using VS2017 15.6.5, if it helps.

**Comment by MBulli** [comment]
MS changed the project type guid of CPS projects because of that we called the wrong routines to set the arguments.

**Comment by thomaslevesque** [comment]
@MBulli thanks! When do you expect to release an update?

**Comment by MBulli** [comment]
@thomaslevesque Today :)

**Comment by thomaslevesque** [comment]
Thanks ! 👍

**Comment by lennartb-** [comment]
We're having the same issue since upgrading WPF .NET 4.6.1 projects to the new project system (https://github.com/dotnet/project-system). It seems to only work every other application start, or in some cases is ignored completely and started with the the last arguments used before the upgrade. I can provide a scrubbed csproj if necessary. Seeing that the original issue was related to the project type GUIDs, we have these in our start-up project:

` <ProjectTypeGuids>{60dc8134-eba5-43b8-bcc9-bb4bc16c2548};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>`

**Comment by MBulli** [comment]
Seems like we have not sufficient rights to write to our json file. I don't see how that could be connected to the project type.

> Access to the path "C:\TFS\Main\Product\Northwind\src\Contoso.Northwind\Contoso.Northwind.args.json"; is denied.

As far as I remember, with TFS a file is read only on disk until you make changes from VS or manually check it out, right?
I guess that's the issue here. Would you mind to do a manually check out of the json file and try to add some commands. Now it should work.
If that's the problem we need to figure out a solution with TFS, which we honestly never tested before ;)

**Comment by MBulli** [comment]
Lets move the discussion to #57
