### ISSUE TITLE
Visual studio crash randomly when clicking in your extension's treeview

### ISSUE THREAD

**Issue by qualialibre** [MBulli/SmartCommandlineArgs#50]
This is a new since a week ago or so.
VS randomly crash solid, when clicking on an item in the treeview of your extension.
Also, clicking on an sub-item will randomly delete it OR move it... or select it !

It sucks cuz your extension is great but it simply does not work !

Have you tested with more than 10 items ? 
I have 50 items, and about 14 root items containing ~7 sub-items each !
All bugs are related to sub-items !!! Random crash, random delete and random move !

All realted crash leave no trace in ActivityLog.xml except "ERROR" !

Input type : Mouse (Allways)

C++ Prioject type (8 projects in the solution)

Microsoft Visual Studio Community 2017 
Version 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
Microsoft .NET Framework
Version 4.7.02556
Installed Version: Community
Smart Commandline Arguments Extension   2.0.3
A Visual Studio Extension which aims to provide a better UI to manage your command line arguments. For additional information, visit https://github.com/MBulli/SmartCommandlineArgs

**Comment by MBulli** [comment]
It's sad to hear that our extension isn't properly working for you. Yesterday we tried to break the tree by adding a lot of items and randomly moving, changing, deleting or switching projects but it never crashed.
We really want to fix that but can't really reproduce your problems. So if you have any hint or something let us now.

Do you have version control support turned on, meaning that the arguments are stored in a json file?

**Comment by MBulli** [comment]
> Also, clicking on an sub-item will randomly delete it OR move it... or select it !

While I'm unable to reproduce the crashes I was able to figure out why the items are jumping.
This is a regression added with the fix for #40.
Lets see how to fix that ...

**Comment by MBulli** [comment]
After some hours of hacking the mouse handling to avoid the jumps of the entries I also found the VS crash!

The crash happens when you drag an element into an empty project. I suspect that the random drag and drop operations caused by the regression in #40 sometimes hits an empty project and causes that crash.

Now that we can reproduce the problems we can finally fix them!

@qualialibre In the mean time you can downgrade to v2.0.2 as the fix for #40 is not included in that release. In addition it would be interesting to know if #47 occurs on that version as well.
