### ISSUE TITLE
Add new button fails sometimes

### ISSUE THREAD

**Issue by pps83** [MBulli/SmartCommandlineArgs#52]
When I click that "+" to add new cmd line I get this:
![image](https://user-images.githubusercontent.com/1614246/39658176-68370480-4fc5-11e8-9fea-abd9e8cc644a.png)

smart cmd line version is 2.0.3 vs 2015u3

**Comment by pps83** [comment]
... and when I restarted VS I got this:

![image](https://user-images.githubusercontent.com/1614246/39658200-ae718eb6-4fc5-11e8-8e86-0826d2d265ce.png)

**Comment by MBulli** [comment]
Possible duplicate with #47. However, we can't reproduce the problem so any hints when this error occurs would help us!

**Comment by pps83** [comment]
In my case it's 100% repro, it just does not work anymore for me. Are there any logs that I could send or anything like that?

**Comment by MBulli** [comment]
You have to enable the ActivityLog in VS and we'll write a lot stuff into it. Hopefully we can finally find that bug! [Here's how you enable the log.](https://github.com/MBulli/SmartCommandlineArgs/wiki/Debug-Log)

**Comment by MBulli** [comment]
Hey @pps83 anything new on this issue?

**Comment by null77** [comment]
This has been happening to us too. It's a bit tricky because it seems to fix itself on a restart and only happen after being run for a while. I'll try turning on logging.

**Comment by pps83** [comment]
Here's [ActivityLog.xml](https://www.pastiebin.com/5b03453b4c3ff)

Seems like you are looking for this line:

```
  <entry>
    <record>747</record>
    <time>2018/05/21 21:56:25.178</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>Failed to get active configuration name for project &apos;Miscellaneous Files&apos; with error &apos;System.InvalidCastException: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE))&#x000D;&#x000A;   at EnvDTE.Project.get_ConfigurationManager()&#x000D;&#x000A;   at SmartCmdArgs.VisualStudioHelper.GetMSBuildPropertyValue(IVsHierarchy hierarchy, String propName) in D:\Source\SmartCommandlineArgs\SmartCmdArgs\SmartCmdArgs\VisualStudioHelper.cs:line 221&apos;</description>
  </entry>
```

Note, that it's 4002 error, in screenshot it was 4005. Also, I have no idea about that "Miscellaneous Files" project and where it comes from.

**Comment by MBulli** [comment]
This error should be fine. We have a try/catch block around that one but log the exceptions. It shouldn't surface to the user.

[Miscellaneous Files is a feature of VS](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/36bhtx7w(v=vs.100)) which was unknown to me.

**Comment by null77** [comment]
Reproed the failure today with ActivityLog enabled. This is the only relevant entry I see:

```  <entry>
    <record>1165</record>
    <time>2018/05/22 11:28:33.529</time>
    <type>Information</type>
    <source>SmartCommandlineArgs</source>
    <description>Tree content changed and VCS support is enabled. Saving all project commands to json file.</description>
  </entry>
```

**Comment by MBulli** [comment]
@null77  Would you mind to give some information about your environment? Latest VS? Projecttype? How big is the solution? How many folders and arguments to you have approximately? Does it only happen when you add a argument? Thanks!

**Comment by MBulli** [comment]
I just uploaded a new version but the problem is not solved.
We still couldn't figure out why and when the issue occurs.
However, I added a messagebox with stacktrace in the suspected method.
Maybe we can find a hint this way ...

**Comment by MBulli** [comment]
@pps83 Can you please check if there is something special about the project in the screenshot (a7a2a36c-3c53-4ccb-b52e-425623e2dda5)?

**Comment by MBulli** [comment]
@pps83 Do you use some git commands before the exception occurs?

**Comment by pps83** [comment]
No, I don't even use git. I use perforce and perhaps there is P4VS plugin that does something when I try to edit something. Normally perforce stores all files in read-only on disk and when you edit a file in VS P4VS (perforce VS plugin) removes readonly attribute on that file and perhaps runs some perforce commands.

**Comment by MBulli** [comment]
Is it possible to temporarily deactivate P4VS just to test if the extensions interfere with each other?

**Comment by pps83** [comment]
I disabled many  extensions but still had the same problem. The only thing that I had and couldn't disable was IncrediBuild (it's not even listed in extensions and updates).

**Comment by null77** [comment]
@MBulli sorry for the slow response. c++ project. Here's a snip of my project Window:

![image](https://user-images.githubusercontent.com/541607/40943067-f13322b2-681d-11e8-9b73-d2782c7b8f0d.png)

Are you using the latest VS 2017 update?

**Comment by pps83** [comment]
I'm using vs2015 up 3

**Comment by MBulli** [comment]
Okay, what we know at the moment:
`IVsSolution2.GetProjectOfGuid()` returns `E_FAIL` for some reason.
This method is actually quite simple, it just returns the `IVsHierachy` of a project with the given Guid.
In my tests it returned E_FAIL if the project is unloaded or does not exist.
@pps83 Do you have any unloaded projects? Could you please look up the project in the error box above (a7a2a36c-3c53-4ccb-b52e-425623e2dda5) in your solution file and tell me its type?

We call this method if anything in the tree changes, not only for the + button but even if you change the value of an argument. It is weird, that the exception only occurs if the + button was clicked.

The issue occurs on both VS 2015 & 2017. Irame has the same exception sometimes in VS2017, but was unable to reproduce it at all. I'm not using the extension on my daily work anymore and I wasn't able to reproduce the problem in my tests.

As far as I know Irame isn't using any special extensions besides Reshaper, hence it is unlikely that the problem is caused by another extension.

This issue really starts to give me a headache...

Currently we save all json files if something was changed in the tree. I'm planing to only save the json of the affected project. Maybe this fixes the bug as a side effect. Nevertheless it would be great to understand the problem. Another 'fix' would be to silently ignore the error, but I don't know the implications of that, maybe the json files won't be persisted anymore ...

**Comment by null77** [comment]
MBulli: you could try making a c++ project and leaving the MSVC project open for quite some time. It usually only repros if I leave the window open more than a day.

**Comment by Irame** [comment]
@pps83 @null77 Please try out this version. We maybe have a workaround. Let us know if the exception is gone. We still have trouble to reliable reproduce the problem.

[SmartCmdArgs_v2.0.4.1.vsix.zip](https://github.com/MBulli/SmartCommandlineArgs/files/2073828/SmartCmdArgs_v2.0.4.1.vsix.zip)

**Comment by pps83** [comment]
I only see that a reference to `425623e2dda5`
in vc.db file C:\USERS\USER\APPDATA\ROAMING\MICROSOFT\VISUALSTUDIO\14.0\SINGLEFILEISENSE\_SFI_D976CC9E-B9D8-4131-A52E-CB8635D5AA8E_.VCXPROJA7A2A36C3C534CCBB52E`425623E2DDA5`

C:\USERS\USER\APPDATA\ROAMING\MICROSOFT\VISUALSTUDIO\14.0\SINGLEFILEISENSE\_SFI_D976CC9E-B9D8-4131-A52E-CB8635D5AA8E_.VCXPROJ is
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectName>Miscellaneous Files</ProjectName>
    <ProjectGuid>{a7a2a36c-3c53-4ccb-b52e-425623e2dda5}</ProjectGuid>
    <ISenseProject>true</ISenseProject>
    <Keyword>SingleFileISense</Keyword>
    <UseDefaultPropertyPageSchemas>false</UseDefaultPropertyPageSchemas>
    <PropertyManagerSupported>false</PropertyManagerSupported>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v140</PlatformToolset>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ItemGroup>
    <PropertyPageSchema Include="$(VCTargetsPath)$(LangID)\ProjectItemsSchema.xml" />
    <PropertyPageSchema Include="$(VCTargetsPath)$(LangID)\isense_general.xml">
      <Context>File;Project</Context>
    </PropertyPageSchema>
  </ItemGroup>
  <ItemGroup>
    <ClCompile Include="..\..\..\..\..\..\..\..\work\Branches\fsdfads.cpp" />
    <ClCompile Include="..\..\..\..\..\..\..\..\work\Branches\fdsafdsahk.c" />
  </ItemGroup>
  <PropertyGroup>
    <!-- Disable project retargeting -->
    <VCProjectUpgraderObjectName>NoUpgrade</VCProjectUpgraderObjectName>
  </PropertyGroup>
</Project>```

no idea where this project comes from

**Comment by MBulli** [comment]
Let me explain what we found yesterday and what we did in 53fc6a609809535ed9fd749c2604b0a932867a55.

We noticed yesterday that the guid of the failing project is always a7a2a36c-3c53-4ccb-b52e-425623e2dda5. A quick google of that guid gave only two (!) hits. A strange github repo and a forum thread where someone has issues with source control in combination with a new feature in VS2015 called single file IntelliSense ([see here](https://blogs.msdn.microsoft.com/vcblog/2015/04/29/single-file-intellisense-and-other-ide-improvements-in-vs2015/)). 

It turns out that MS added this feature in order to allow you to use IntelliSense in files which don't belong to a vcxproj. However, it seems like that MS needs a project to use IntelliSense and this is where these strange projects in AppData come from. To me it looks like that MS creates a pseudo project in the background to implement single file IntelliSense and somehow these pseudo projects, which are supposed to be invisible, find their way into our extension and causes the issue.

It seems that all of these pseudo projects have the same guid from above. Our 'fix' is to ignore projects with this guid. Admitted, this is not the perfect fix but should work for now. So if you try the version Irame posted above the issue should be gone, hopefully. If it works we will do a real release.

**Comment by null77** [comment]
Getting this exception when updating the command line:

![image](https://user-images.githubusercontent.com/541607/41249785-0934246e-6d83-11e8-9353-fd875606ffae.png)

Will try with the workaround version you uploaded. Thanks.

**Comment by null77** [comment]
The error hasn't reproduced since using the workaround version. Seems like it fixed it. Possibly unrelated bug: sometimes I get red highlight flashes when selecting items in the commandline arguments window with the workaround version.

**Comment by MBulli** [comment]
Good to hear!
I'll push a release this weekend.

The red highlight is not a bug but a (debug) feature ;)
We use it to debug focus handling but forgot to disable it for the test version.

**Comment by null77** [comment]
Great! Thank you for the fix.
