### ISSUE TITLE
Latest release won't install in VS2017

### ISSUE THREAD

**Issue by asherber** [MBulli/SmartCommandlineArgs#81]
![image](https://user-images.githubusercontent.com/5248041/55486314-15f3e080-55fa-11e9-81da-b6f2e3b14e39.png)

**Comment by n00bmind** [comment]
Same here!
2015 shows as installable too, but not 2017

**Comment by n00bmind** [comment]
In case it helps, my VS version is 15.7.6 with .NET 4.7.03056.
I could install version 2.0.7 just fine.

**Comment by MBulli** [comment]
@asherber which VS 2017 version do you have exactly?

@n00bmind @asherber It seems that VS is automatically added "15.8.27729.1" as the lowest version for the prerequisite `Microsoft.VisualStudio.Component.CoreEditor`. VS2015 works because it still uses the vsix v2 format which ignores the prerequisites.  

I don't know why it does it. I'll check that tomorrow and will most likely upload a release. Nevertheless, it is annoying that such issues happen and I'm sorry!

**Comment by asherber** [comment]
I have 15.9.11 -- latest as of yesterday.

**Comment by MBulli** [comment]
That's weird. I expected a older version than 15.8. On my computer I have 15.9.7 and it works. 

Please try the new release: https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.1.2

If it doesn't work would you mind to give us a list of your installed workloads?

**Comment by asherber** [comment]
Thanks, that works for me!

**Comment by MBulli** [comment]
Cool :)
